spring.application.name=bidly-backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://trolley.proxy.rlwy.net:53193/railway}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rzOnesuXFNdajrJWXelLgoOlwkcGJECU}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=${PORT:8083}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.error.include-message=always
server.error.include-binding-errors=always